media:
  - name: logos
    label: Logo files
    input: logos
    output: /logos
    extensions: [svg]

content:
  - name: logos
    label: Logos
    type: collection
    path: data/logos
    format: json
    subfolders: false
    filename: "{year}{month}{day}-{hour}{minute}{second}.json"
    view:
      fields: [name, en, category]
      primary: name
      search: [name, en, category]
      sort: [name, category]
      default:
        sort: name
        order: asc
    fields:
      - name: file
        label: Logo (SVG)
        type: image
        required: true
        options:
          media: logos
          extensions: [svg]
      - name: name
        label: Name (Persian)
        type: string
        required: true
      - name: en
        label: Name (English)
        type: string
      - name: category
        label: Category
        type: select
        required: true
        options:
          values:
            - name: حمل‌ونقل و سفر
              label: Transport & Travel
            - name: غذا
              label: Food
            - name: خرید و فروش
              label: Shopping
            - name: مخابرات
              label: Telecom
            - name: رسانه و سرگرمی
              label: Media & Entertainment
            - name: فناوری و اپلیکیشن
              label: Tech & Apps
            - name: آموزش
              label: Education
            - name: طراحی و خلاقیت
              label: Design & Creative

settings:
  commit:
    templates:
      create: "Add {filename}"
      update: "Update {filename}"
      delete: "Remove {filename}"
